/**
 * Expo Config Plugin: withReceiptBitmap
 * ======================================
 * Injects the ReceiptBitmapModule native Android module during `expo prebuild`.
 *
 * The `mobile/android/` directory is gitignored (regenerated by EAS via prebuild),
 * so any manually-added native files are lost in EAS builds. This plugin ensures
 * the native module is always present by:
 *
 * 1. Writing ReceiptBitmapModule.kt and ReceiptBitmapPackage.kt to the android source dir
 * 2. Modifying MainApplication.kt to register the package
 * 3. Appending Proguard keep rules to prevent R8 from stripping the module
 */

const { withDangerousMod, withMainApplication } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// ---------------------------------------------------------------------------
// Step 1: Modify MainApplication.kt to register ReceiptBitmapPackage
// ---------------------------------------------------------------------------
function withReceiptBitmapMainApplication(config) {
  return withMainApplication(config, (config) => {
    let contents = config.modResults.contents;

    // Only add if not already present
    if (!contents.includes('ReceiptBitmapPackage')) {
      // Add the package registration after PackageList(this).packages
      contents = contents.replace(
        /val packages = PackageList\(this\)\.packages/,
        `val packages = PackageList(this).packages\n            // Custom native module for rendering receipt text to bitmap image\n            // (thermal printers cannot render Telugu in text mode)\n            packages.add(ReceiptBitmapPackage())`
      );

      config.modResults.contents = contents;
    }

    return config;
  });
}

// ---------------------------------------------------------------------------
// Step 2: Write Kotlin source files and Proguard rules
// ---------------------------------------------------------------------------
function withReceiptBitmapFiles(config) {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const androidDir = path.join(projectRoot, 'android');
      const javaDir = path.join(
        androidDir,
        'app',
        'src',
        'main',
        'java',
        'com',
        'groceryone',
        'app'
      );

      // Ensure directory exists
      fs.mkdirSync(javaDir, { recursive: true });

      // Write ReceiptBitmapPackage.kt
      fs.writeFileSync(
        path.join(javaDir, 'ReceiptBitmapPackage.kt'),
        RECEIPT_BITMAP_PACKAGE_KT,
        'utf-8'
      );

      // Write ReceiptBitmapModule.kt
      fs.writeFileSync(
        path.join(javaDir, 'ReceiptBitmapModule.kt'),
        RECEIPT_BITMAP_MODULE_KT,
        'utf-8'
      );

      // Append Proguard keep rules
      const proguardPath = path.join(androidDir, 'app', 'proguard-rules.pro');
      if (fs.existsSync(proguardPath)) {
        const proguardContent = fs.readFileSync(proguardPath, 'utf-8');
        if (!proguardContent.includes('ReceiptBitmapModule')) {
          fs.appendFileSync(
            proguardPath,
            PROGUARD_RULES,
            'utf-8'
          );
        }
      }

      return config;
    },
  ]);
}

// ---------------------------------------------------------------------------
// Main plugin entry point
// ---------------------------------------------------------------------------
function withReceiptBitmap(config) {
  config = withReceiptBitmapMainApplication(config);
  config = withReceiptBitmapFiles(config);
  return config;
}

module.exports = withReceiptBitmap;

// ---------------------------------------------------------------------------
// Embedded Kotlin source: ReceiptBitmapPackage.kt
// ---------------------------------------------------------------------------
const RECEIPT_BITMAP_PACKAGE_KT = `package com.groceryone.app

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/**
 * ReactPackage that registers the ReceiptBitmapModule native module.
 * Added to MainApplication.getPackages() for manual linking.
 */
class ReceiptBitmapPackage : ReactPackage {
    override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> =
        listOf(ReceiptBitmapModule(reactContext))

    override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> =
        emptyList()
}
`;

// ---------------------------------------------------------------------------
// Embedded Kotlin source: ReceiptBitmapModule.kt
// ---------------------------------------------------------------------------
const RECEIPT_BITMAP_MODULE_KT = `package com.groceryone.app

import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Rect
import android.graphics.Typeface
import android.text.TextPaint
import android.text.TextUtils
import android.util.Base64
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import java.io.ByteArrayOutputStream

/**
 * Native module that renders receipt text to a base64 PNG bitmap.
 *
 * Thermal receipt printers use single-byte codepages (CP437/Windows-1252)
 * and cannot render multi-byte scripts like Telugu. This module uses Android's
 * native Canvas to render the receipt text (including Telugu) to a bitmap image,
 * which is then sent to the printer via printImageBase64().
 *
 * ## Thermal printer optimizations
 *
 * - **Anti-aliasing disabled**: Thermal printers are 1-bit devices (each dot is
 *   black or white). Anti-aliased gray edge pixels cause ghosting/doubling when
 *   the printer library thresholds them to 1-bit. Disabling anti-aliasing ensures
 *   every pixel is pure black or pure white.
 * - **Bold typeface**: All text is rendered in bold for thicker character strokes.
 *   Thicker strokes are more robust at 203 DPI thermal printer resolution and
 *   less susceptible to heat variation and dot spacing inconsistencies.
 * - **1-bit threshold**: After rendering, all pixels are explicitly thresholded to
 *   pure black or white as a safety net against device-specific sub-pixel rendering.
 *
 * ## Tab-separated column rendering (pixel-based)
 *
 * Lines containing TAB characters are rendered with pixel-based column
 * positioning. Each column gets a proportional slice of the bitmap width
 * (e.g., 10%/32%/12%/20%/26% for 5-column layout). This guarantees perfect
 * alignment regardless of script \u2014 Telugu, English, or mixed text.
 *
 * - 5-column (NO|ITEM|QTY|RATE|AMT): first 3 left-aligned, last 2 right-aligned
 * - 2-column (label|value): label left-aligned, value right-aligned
 * - Long text is ellipsized using TextUtils.ellipsize() which respects
 *   Telugu conjunct boundaries (no mid-character breaks)
 *
 * ## Always-scale rendering
 *
 * Non-tabular lines (dividers, labels, footer) are always scaled to fill
 * the full bitmap width. There is no software margin \u2014 the thermal printer
 * itself provides a physical non-printable margin at the paper edges.
 *
 * ## Bold+large rendering for marked lines
 *
 * Lines prefixed with U+0001 (SOH) are rendered at 1.4x the base font size
 * and horizontally centered. The marker is stripped before rendering.
 *
 * Font fallback chain:
 * - ASCII characters -> Typeface.MONOSPACE Bold (Droid Sans Mono Bold)
 * - Telugu characters -> Noto Sans Telugu Bold (automatic Android fallback)
 */
class ReceiptBitmapModule(reactContext: ReactApplicationContext) :
    ReactContextBaseJavaModule(reactContext) {

    override fun getName(): String = "ReceiptBitmap"

    /** Format marker: lines prefixed with this char are rendered bold+large */
    private val BOLD_LARGE_MARKER = '\\u0001'

    /** Scale factor for bold+large lines relative to base font size */
    private val BOLD_SCALE = 1.4f

    /** Format marker: lines prefixed with this char are centered at normal font size */
    private val CENTER_MARKER = '\\u0002'

    /** Format marker: tab lines prefixed with this char are rendered bold+large (1.3x) */
    private val BOLD_TAB_MARKER = '\\u0003'

    /** Scale factor for bold tab lines (grand total) relative to base font size */
    private val BOLD_TAB_SCALE = 1.3f

    /**
     * Render pre-formatted receipt text to a base64-encoded PNG image.
     *
     * @param text     Pre-formatted receipt text with newlines and column alignment
     * @param width    Image width in pixels (576 for 80mm paper, 384 for 58mm)
     * @param fontSize Font size in pixels (controls character width for column alignment)
     * @param promise  Resolves with base64 PNG string, rejects on error
     */
    @ReactMethod
    fun renderTextToImage(text: String, width: Int, fontSize: Float, promise: Promise) {
        try {
            val paint = TextPaint().apply {
                color = Color.BLACK
                textSize = fontSize
                typeface = Typeface.create(Typeface.MONOSPACE, Typeface.BOLD)
                isAntiAlias = false
            }

            // Use full bitmap width \u2014 thermal printer provides its own physical margin
            val effectiveWidth = width

            // Split text into lines first to find the longest line for scaling
            val lines = text.split("\\n")

            // For max line length, only consider normal (unmarked, non-tab) lines.
            // Bold+large, centered, and tab-columnar lines are rendered independently.
            val maxLineLength = lines
                .filter {
                    !it.startsWith(BOLD_LARGE_MARKER) &&
                    !it.startsWith(CENTER_MARKER) &&
                    !it.startsWith(BOLD_TAB_MARKER) &&
                    !it.contains('\\t')
                }
                .maxOfOrNull { it.length }?.coerceAtLeast(1) ?: 1

            // Monospace character width \u2014 all ASCII chars have this exact advance width.
            var charWidth = paint.measureText("M")

            // Always scale to fill the full bitmap width.
            // This eliminates right-side empty space for clean edge-to-edge rendering.
            val requiredWidth = maxLineLength * charWidth
            val scaleFactor = effectiveWidth.toFloat() / requiredWidth
            paint.textSize = fontSize * scaleFactor
            charWidth = paint.measureText("M")

            // Save the base (scaled) font size for bold+large calculations
            val baseFontSize = paint.textSize

            // Line height from font metrics for consistent vertical spacing
            val fontMetrics = paint.fontMetrics
            val lineHeight = fontMetrics.descent - fontMetrics.ascent + fontMetrics.leading
            // Ensure minimum line height to avoid cramped text (use actual/scaled font size)
            val effectiveLineHeight = if (lineHeight < paint.textSize * 1.2f) paint.textSize * 1.2f else lineHeight

            // Bold+large line height
            val boldLineHeight = effectiveLineHeight * BOLD_SCALE
            // Bold tab line height (grand total)
            val boldTabLineHeight = effectiveLineHeight * BOLD_TAB_SCALE

            // Calculate total height with variable line heights for marked lines
            var totalHeight = effectiveLineHeight // top padding
            for (line in lines) {
                totalHeight += when {
                    line.startsWith(BOLD_LARGE_MARKER) -> boldLineHeight
                    line.startsWith(BOLD_TAB_MARKER) -> boldTabLineHeight
                    else -> effectiveLineHeight
                }
            }

            val bitmap = Bitmap.createBitmap(width, totalHeight.toInt(), Bitmap.Config.ARGB_8888)
            val canvas = Canvas(bitmap)
            canvas.drawColor(Color.WHITE)

            // First baseline: offset by ascent (ascent is negative, so negate it)
            var y = -fontMetrics.ascent + effectiveLineHeight * 0.1f

            for (line in lines) {
                if (line.startsWith(BOLD_LARGE_MARKER)) {
                    // Bold+large line: strip marker, render centered at 1.4x bold font
                    val content = line.substring(1)
                    renderBoldLargeLine(canvas, paint, content, y, effectiveWidth, baseFontSize)
                    y += boldLineHeight
                } else if (line.startsWith(CENTER_MARKER)) {
                    // Centered line: strip marker + space padding, render centered at normal font
                    val content = line.substring(1).trim()
                    renderCenteredLine(canvas, paint, content, y, effectiveWidth)
                    y += effectiveLineHeight
                } else if (line.startsWith(BOLD_TAB_MARKER)) {
                    // Bold tab line: strip marker, render at 1.3x font with tab column layout
                    renderBoldTabLine(canvas, paint, line, y, effectiveWidth, baseFontSize)
                    y += boldTabLineHeight
                } else if (isDividerLine(line)) {
                    // Graphical divider: edge-to-edge rect instead of text characters
                    renderDividerLine(canvas, paint, line[0], y, effectiveWidth, effectiveLineHeight)
                    y += effectiveLineHeight
                } else if (line.contains('\\t')) {
                    // Tab-separated line: render with pixel-based column positioning
                    renderTabColumnarLine(canvas, paint, line, y, effectiveWidth)
                    y += effectiveLineHeight
                } else if (line.isNotEmpty() && line[0] == '|' && line[line.length - 1] == '|') {
                    // Pipe-delimited line: render with fixed-position columns
                    renderPipeDelimitedLine(canvas, paint, line, y, charWidth)
                    y += effectiveLineHeight
                } else {
                    // Non-pipe line: render as plain text
                    canvas.drawText(line, 0f, y, paint)
                    y += effectiveLineHeight
                }
            }

            // Convert to pure 1-bit black/white for thermal printer.
            val w = bitmap.width
            val h = bitmap.height
            val pixelBuffer = IntArray(w * h)
            bitmap.getPixels(pixelBuffer, 0, w, 0, 0, w, h)
            for (i in pixelBuffer.indices) {
                val r = (pixelBuffer[i] shr 16) and 0xFF
                val g = (pixelBuffer[i] shr 8) and 0xFF
                val b = pixelBuffer[i] and 0xFF
                val luminance = (0.299 * r + 0.587 * g + 0.114 * b).toInt()
                pixelBuffer[i] = if (luminance < 128) Color.BLACK else Color.WHITE
            }
            bitmap.setPixels(pixelBuffer, 0, w, 0, 0, w, h)

            val stream = ByteArrayOutputStream()
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream)
            bitmap.recycle()

            val base64 = Base64.encodeToString(stream.toByteArray(), Base64.NO_WRAP)
            promise.resolve(base64)
        } catch (e: Exception) {
            promise.reject("RENDER_ERROR", "Failed to render receipt bitmap: \${e.message}", e)
        }
    }

    /**
     * Render a bold+large line, horizontally centered in the bitmap.
     */
    private fun renderBoldLargeLine(
        canvas: Canvas,
        paint: TextPaint,
        content: String,
        y: Float,
        bitmapWidth: Int,
        baseFontSize: Float
    ) {
        val originalTypeface = paint.typeface
        val originalTextSize = paint.textSize

        paint.typeface = Typeface.create(Typeface.MONOSPACE, Typeface.BOLD)
        paint.textSize = baseFontSize * BOLD_SCALE

        val textWidth = paint.measureText(content)
        if (textWidth > bitmapWidth) {
            val scaleFactor = bitmapWidth.toFloat() / textWidth
            paint.textSize = paint.textSize * scaleFactor
        }

        val finalWidth = paint.measureText(content)
        val x = (bitmapWidth - finalWidth) / 2f

        canvas.drawText(content, x.coerceAtLeast(0f), y, paint)

        paint.typeface = originalTypeface
        paint.textSize = originalTextSize
    }

    /**
     * Render a line horizontally centered in the bitmap at normal font size.
     */
    private fun renderCenteredLine(
        canvas: Canvas,
        paint: TextPaint,
        content: String,
        y: Float,
        bitmapWidth: Int
    ) {
        val textWidth = paint.measureText(content)
        val x = (bitmapWidth - textWidth) / 2f
        canvas.drawText(content, x.coerceAtLeast(0f), y, paint)
    }

    /**
     * Check if a line consists entirely of the same divider character ('=' or '-').
     */
    private fun isDividerLine(line: String): Boolean {
        if (line.isEmpty()) return false
        val ch = line[0]
        return (ch == '=' || ch == '-') && line.all { it == ch }
    }

    /**
     * Render a divider line as graphical bars spanning the full bitmap width.
     */
    private fun renderDividerLine(
        canvas: Canvas,
        paint: TextPaint,
        ch: Char,
        y: Float,
        bitmapWidth: Int,
        lineHeight: Float
    ) {
        val centerY = y - lineHeight * 0.3f
        if (ch == '=') {
            val barH = lineHeight * 0.12f
            val gap = lineHeight * 0.1f
            canvas.drawRect(0f, centerY - gap / 2 - barH, bitmapWidth.toFloat(), centerY - gap / 2, paint)
            canvas.drawRect(0f, centerY + gap / 2, bitmapWidth.toFloat(), centerY + gap / 2 + barH, paint)
        } else {
            val barH = lineHeight * 0.08f
            canvas.drawRect(0f, centerY - barH / 2, bitmapWidth.toFloat(), centerY + barH / 2, paint)
        }
    }

    /**
     * Render a tab-separated line at 1.3x font size for emphasis (e.g., GRAND TOTAL).
     */
    private fun renderBoldTabLine(
        canvas: Canvas,
        paint: TextPaint,
        line: String,
        y: Float,
        bitmapWidth: Int,
        baseFontSize: Float
    ) {
        val content = line.substring(1)
        val originalTextSize = paint.textSize
        paint.textSize = baseFontSize * BOLD_TAB_SCALE
        renderTabColumnarLine(canvas, paint, content, y, bitmapWidth)
        paint.textSize = originalTextSize
    }

    /**
     * Render a tab-separated line with pixel-based column positioning.
     *
     * Column proportions by count:
     * - 5 columns (NO|ITEM|QTY|RATE|AMT): 8%/38%/11%/18%/25%
     * - 2 columns (ITEM|QTY): 70%/30%
     * - Other: equal distribution
     */
    private fun renderTabColumnarLine(
        canvas: Canvas,
        paint: TextPaint,
        line: String,
        y: Float,
        bitmapWidth: Int
    ) {
        val cells = line.split('\\t')
        val proportions = when (cells.size) {
            5 -> floatArrayOf(0.08f, 0.38f, 0.11f, 0.18f, 0.25f)
            2 -> floatArrayOf(0.70f, 0.30f)
            else -> FloatArray(cells.size) { 1.0f / cells.size }
        }

        var x = 0f
        val padding = 2f
        for (i in cells.indices) {
            val colWidth = bitmapWidth * proportions[i]
            val cellText = cells[i].trim()
            val availWidth = colWidth - 2 * padding

            val displayText = if (availWidth > 0 && paint.measureText(cellText) > availWidth) {
                TextUtils.ellipsize(cellText, paint, availWidth,
                    TextUtils.TruncateAt.END).toString()
            } else {
                cellText
            }

            val textWidth = paint.measureText(displayText)
            val isRightAligned = when (cells.size) {
                5 -> i >= 3
                else -> i >= 1
            }
            val drawX = if (isRightAligned) {
                x + colWidth - textWidth - padding
            } else {
                x + padding
            }

            canvas.save()
            canvas.clipRect(
                x,
                y + paint.fontMetrics.ascent,
                x + colWidth,
                y + paint.fontMetrics.descent
            )
            canvas.drawText(displayText, drawX.coerceAtLeast(x), y, paint)
            canvas.restore()

            x += colWidth
        }
    }

    /**
     * Render a pipe-delimited line with fixed-position column separators.
     */
    private fun renderPipeDelimitedLine(
        canvas: Canvas,
        paint: TextPaint,
        line: String,
        y: Float,
        charWidth: Float
    ) {
        val pipePositions = mutableListOf<Int>()
        for (i in line.indices) {
            if (line[i] == '|') pipePositions.add(i)
        }

        for (pipePos in pipePositions) {
            val x = pipePos * charWidth
            canvas.drawText("|", x, y, paint)
        }

        for (i in 0 until pipePositions.size - 1) {
            val startCharPos = pipePositions[i] + 1
            val endCharPos = pipePositions[i + 1]
            if (startCharPos < endCharPos) {
                val cellContent = line.substring(startCharPos, endCharPos)
                val cellStartX = startCharPos * charWidth
                val cellEndX = endCharPos * charWidth

                canvas.save()
                canvas.clipRect(
                    cellStartX,
                    y + paint.fontMetrics.ascent,
                    cellEndX,
                    y + paint.fontMetrics.descent
                )
                canvas.drawText(cellContent, cellStartX, y, paint)
                canvas.restore()
            }
        }
    }
}
`;

// ---------------------------------------------------------------------------
// Proguard keep rules
// ---------------------------------------------------------------------------
const PROGUARD_RULES = `
# ReceiptBitmapModule — native receipt text-to-bitmap renderer for thermal printers
-keep class com.groceryone.app.ReceiptBitmapModule { *; }
-keep class com.groceryone.app.ReceiptBitmapPackage { *; }
`;
